config/routes.rb
Rails.application.routes.draw do
  
#  get 'login', to: 'sessions#new'
  get 'profile', to: 'users#show'
  #get 'users/show'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "homes#index"



####### Adding custom action in bugs controller #######

  resources :bugs do
    collection do
      get :assign_bug
      get :resolved_bug      
    end
  end
  
####### Adding custom action in bugs controller #######


####### Adding custom action in project controller #######

  resources :projects do
  	member do
  		get :add_user
      delete :delete_project_user
  		end
  	end

####### Adding custom action in project controller #######

  resources :projects
  resources :bugs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# my comment
class Project < ApplicationRecord
  has_many  :user_projects
	has_many  :users ,  through:  :user_projects  ,  dependent:  :destroy
	 	has_many :bugs, dependent: :destroy
	 	validates :name, presence: true
	 	accepts_nested_attributes_for :user_projects
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json

  def index
    if current_user.user_type != "Developer"
      @projects = Project.all
    else
      @projects = current_user.projects
    end
    authorize @projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    authorize @project    
    @bugs = @project.bugs

    @project_users = @project.users
  end

  # GET /projects/new
  def new
    @project = Project.new
    @users = User.where(user_type: 'Developer')
    @project.user_projects.build

    authorize @project
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    @users = User.where(user_type: 'Developer')
    @project.user_projects.build
    authorize @project
    # @project.user_projects.build
  end

  def add_user
    @project = Project.find(params[:id])
    @users = User.where.not(user_type: "Manager")
    authorize @project

    if params[:user_id].present?
      UserProject.create!(user_id: params[:user_id], project_id: params[:id])
      flash[:notice] = "User Added Successfully."
    end
  end

  # POST /projects
  # POST /projects.json
  def create
      # if current_user.projects << @project
    @project = Project.new(project_params)


    authorize @project

    respond_to do |format|


      if @project.save!

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    authorize @project    
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    authorize @project    
    @project.destroy
    authorize @project
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_project_user
    @project = Project.find(params[:id])

    @project.bugs.each do |bug|
      puts '----------------------'
      puts bug.developer_id.inspect
      puts params[:user_id].inspect
      puts (bug.developer_id == params[:user_id]).inspect
      puts '----------------------'



      if bug.developer_id.to_i == params[:user_id].to_i
        bug.update!(developer_id: nil)
      end
    end

  
    user_proj = UserProject.find_by(project_id: params[:id] , user_id: params[:user_id])
    if user_proj.destroy
      redirect_to @project
    end
    
    authorize @project
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
      authorize @project
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
       params.require(:project).permit(:name, user_projects_attributes: [[:user_id, :project_id]])
     end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :user_projects do |builder| %>
  <fieldset>
    <%= builder.label :user_id, "Add User" %>
    <%= builder.select :user_id,options_for_select(@users.collect { |user| [user.name, user.id] }) %>
  </fieldset>

  <% end %> 


  <%#= f.fields_for :user_projects do |builder| %>
    <%#= builder.collection_check_boxes :user_id, @users,:id, :name do |b| %>
    <%#= b.label {b.check_box + b.text} %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/add_user.html.erb
<%= form_tag add_user_project_path(@project.id) , method: :GET  do  %>
<div class="field">
	<%= label_tag :Add_Developer %>
  <%= select_tag :user_id, options_for_select(@users.collect{|user| [user.name,user.id]}) %>
</div>
  
<div class="actions">
  <%= submit_tag "Add User" %>
</div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path,class: "btn btn-info" %>

app/views/projects/index.html.erb
<html>
<!--   <head>
    <title>Projects</title>
  </head> -->
  <body>
    <div class="container">
      <h2>
        Projects

        <p>
          
          <% if policy(Project).new? %>
          <%= link_to 'New Project', new_project_path,class: "btn btn-primary pull-right" %>
          <% end %>

        </p>
      </h2>
      <table class="table">
        <thead>
          <tr>
            <th>Project Name</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>

            <td>
              <%= link_to 'Report Bug', new_bug_path , class: "btn btn-info" if policy(Bug).new?  %>
              <%= link_to("Show Bugs & Users",project_path(project.id), class: "btn btn-info") %>
              <%= link_to "Add User", add_user_project_path(project.id) , class: "btn btn-info" if policy(Project).add_user?%> 
            </td>
            <td> <%= link_to 'Edit', edit_project_path(project),class: "btn btn-info" if policy(Project).edit? %>
            <%= link_to 'Destroy', project,class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?'} if policy(Project).destroy? %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>
   </body>
</html>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="container">
    <h2><%= @project.name %> Bugs</h2>
    <table class="table table-dark">
      <thead>
        <tr>
          <th>Project</th>
          <th>Bug Title</th>
          <th>Deadline</th>
          <th>Screenshot</th>
          <th>Status</th>
          <th>Type</th>
          <th>Created By User ID</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @bugs.each do |bug| %>
        <tr>
          <td><%= bug.project.name%></td>
         
          <td><%= bug.title %></td>
          <td><%= bug.deadline %></td>
          <td><%= bug.screenshot %></td>
          <td><%= bug.status %></td>
          <td><%= bug.bug_type %></td>
          <td><%= bug.user_id %></td>
<!--           <td><%#= link_to 'Edit', edit_project_path(@project) ,class: "btn btn-info"if policy(Project).edit? %></td> -->
           
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>

<div class="container">
    <h2> <%= @project.name %> Users</h2>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>User</th>
        </tr>
      </thead>
      <tbody>
        <% @project_users.each do |project_user| %>
        <tr>
          <td>
            <%= project_user.name %>
          </td>
          
          <td>
          <%=link_to "Remove",delete_project_user_project_path(user_id: project_user.id), :method => :delete, :class => "delete", :confirm => "Are you sure ?",class: "btn btn-danger" if policy(Project).delete_project_user?%>  

            <%#= link_to 'Remove', method: :delete, data: { confirm: 'Are you sure?'} %>
          </td>

        </tr>
        
        <% end %>

      </tbody>
    </table>
</div>

<%= link_to 'Back', projects_path ,class: "btn btn-info"%>