config/routes.rb
Rails.application.routes.draw do
  
#  get 'login', to: 'sessions#new'
  get 'profile', to: 'users#show'
  #get 'users/show'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "homes#index"



####### Adding custom action in bugs controller #######

  resources :bugs do
    collection do
      get :assign_bug
      get :resolved_bug      
    end
  end
  
####### Adding custom action in bugs controller #######


####### Adding custom action in project controller #######

  resources :projects do
  	member do
  		get :add_user
      delete :delete_project_user
  		end
  	end

####### Adding custom action in project controller #######

  resources :projects
  resources :bugs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
class Bug < ApplicationRecord
	belongs_to :user
	belongs_to :project

	has_one :assigned_to, primary_key: "developer_id", class_name:"User", foreign_key: "id"


	validates :title, presence: true, uniqueness: true
	validates :status, presence: true
	validates :bug_type, presence: true

	mount_uploader :screenshot, ImageUploader

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    
    if current_user.user_type != "Developer"
      @bugs = Bug.all
      authorize @bugs
    ##### showing assigned project bugs of all users ###########
    else
      @bugs = Array.new
      current_user.projects.find_each do |project|
        project.bugs.each do |bug|
          @bugs << bug
        end
      end
    end
    @bugs.each do |bug|
      authorize bug
    end

    # respond_to  do  |format|
    #         format.html {render :index }
    #             format.json { render  :index }
            
    #     end

    # to show current user assigned project bugs
    # else
    #   @bugs = current_user.resolved_bugs #resolved bugs method defined in User model :P
    #   authorize @bugs
    # end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show  
#    @project
  end


  # GET /bugs/new
  def new
    
    if current_user.user_type != "Developer"
      @projects = Project.all
    else
      @projects = current_user.projects
    end
    
    @bug = Bug.new
    @bug_types = ["feature","bug"]

    @assign_bugs_to_users = User.all
    authorize @bug
    
  end

  # GET /bugs/1/edit
  def edit
    if current_user.user_type != "Developer"
      @projects = Project.all
    else
      @projects = current_user.projects
    end
    @bug_types = ["feature","bug"]

     @assign_bugs_to_users = User.all    
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    @bug.user_id = current_user.id
    authorize @bug

    if @bug.save
      redirect_to @bug, notice: 'Bug was successfully created.'
    else
      redirect_to new_bug_path, flash: {danger: @bug.errors.full_messages }
    end
  end

  def assign_bug

    @bug = Bug.find(params[:id])
    authorize @bug

    @bug.developer_id = current_user.id
    @bug.status = "started"

    if @bug.save
      render json: { message: "Succesfully Assigned.",name: current_user.name , status: 200}.to_json
    else
      render json: { message: "Error occured.", status: 500}
    end

  end

  def resolved_bug
    @bug = Bug.find(params[:id])
    authorize @bug
    @bug.status = "completed"

    if @bug.save
      render json: { message: "Bug Resolved.", status: 200}.to_json
    else
      render json: { message: "Error Occured.", status: 500}
    end

  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
      authorize @bug
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :deadline, :screenshot, :status, :bug_type, :user_id, :developer_id, :project_id)
    end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_bugs_index.html.erb
<div class="container">
  <h2>Bugs</h2>
  <table class="table" >
    <thead>
      <tr>
        <th>Created By</th>
        <th> Assigned To</th>
        <th>Project</th>
        <th>Title</th>
        <th>Deadline</th>
        <th>Screenshot</th>
        <th>Status</th>
        <th>Type</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody id="bugs-table-body">
      <% bugs.each do |bug| %>
      <tr id = '<%= bug.id %>'>
        <td><%= bug.user.name%></td>
        <td id="assigned_to_id_<%= bug.id %>"><%= bug.assigned_to.name rescue "" %></td>
        <td><%= bug.project.name %></td>
        <td><%= bug.title %></td>
        <td><%= bug.deadline %></td>
        <td><%= image_tag bug.screenshot_url.to_s %></td>
        <td id="bug_status_id_<%= bug.id %>"><%= bug.status %></td>
        <td ><%= bug.bug_type %></td>
        <% if(!bug.assigned_to.present? && policy(Bug).assign_bug?) %>
          <td><button class="btn btn-primary assign_bug_button" id= "bug_<%= bug.id %>">Assign Bug</button>
          </td>
        <% end %> 
        <% if(bug.assigned_to.present? && bug.status == "started" && policy(Bug).assign_bug?) %>
          <td>
            <button class="btn btn-warning change_status_button" id= "bug_<%= bug.id %>">Resolved ?</button>
          </td>
        <% end %>
        <td><%= link_to 'Edit', edit_bug_path(bug),class: "btn btn-info" if policy(Bug).edit? %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" if policy(Bug).destroy? %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bugs/_form.html.erb
<%= form_for(bug) do |f| %>
  <% if bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.select(:project_id,options_for_select(@projects.collect{|project| [project.name,project.id]})) %> 
  </div>

  <div class="field">
    <%= f.label :developer_id,'Assign Bug To User' %>
    <%= f.select(:developer_id, options_for_select(@assign_bugs_to_users.collect{|user| [user.name,user.id] if user.user_type != "Manager" }.compact ), :include_blank => true , class: "form-control")%>
    
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title , class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :deadline %>
    <%= f.date_field :deadline, min: Date.current , class: "form-control" %>
  </div>


  <div class="field">
    <%= f.file_field :screenshot, accept: 'image/png,image/gif' %>
  </div>

  <div class="field">
    <%= f.label :bug_type %>
     <%= f.select :bug_type, @bug_types, {}, :id =>:bug_type_id, include_blank: true %> 
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, ["new","started","completed"],{},:id => :status_id,include_blank: false %>
  </div>

     <%#= f.text_field :status %>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/assign_bug.html.erb
<div class="container">
	<h2>Bugs Assigned to <%#= @bug.assigned_to.name %> </h2>
	<table class="table">
		<thead>
			<tr>
				<th>Created By</th>
				<th>Assigned To</th>
				<th>Project</th>
				<th>Bug Title</th>
				<th>Deadline</th>
				<th>Screenshot</th>
				<th>status</th>
				<th>Type</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @bug.user.name%></td>
        <td><%= @bug.assigned_to.name rescue ""%></td>
        <td><%= @bug.project.name %>  </td>
        <td><%= @bug.title %></td>
        <td><%= @bug.deadline %></td>
        <td><%= image_tag @bug.screenshot_url.to_s %></td>
        <td><%= @bug.status %></td>
        <td><%= @bug.bug_type %></td>
			</tr>
		</tbody>
			
	</table>
</div>

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Back', bugs_path,class: "btn btn-info" %>

app/views/bugs/index.html.erb
    <h2>Bugs</h2>
    <table class="table" >
      <thead class="thead-dark">
        <tr>
          <th>Created By</th>
          <th> Assigned To</th>
          <th>Project</th>
          <th>Title</th>
          <th>Deadline</th>
          <th>Screenshot</th>
          <th>Status</th>
          <th>Type</th>
<!--           <th>Created By User ID</th> -->
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody id="bugs-table-body">
        <% @bugs.each do |bug| %>
        <tr id = '<%= bug.id %>'>
          <td><%= bug.user.name%></td>
          <td id="assigned_to_id_<%= bug.id %>"><%= bug.assigned_to.name rescue "" %></td>
          <td><%= bug.project.name %></td>
          <td><%= bug.title %></td>
          <td><%= bug.deadline %></td>
          <td><%= image_tag bug.screenshot_url.to_s %></td>
          <td id="bug_status_id_<%= bug.id %>"><%= bug.status %></td>
          <td ><%= bug.bug_type %></td>
          <% if(!bug.assigned_to.present? && policy(Bug).assign_bug?) %>
            <td>
              <button class="btn btn-primary assign_bug_button" id= "bug_<%= bug.id %>">Assign Bug</button>
            </td>
          <% end %> 
<!--           <%# if(bug.assigned_to.present? && bug.status == "started" && policy(Bug).assign_bug?) %>
            <td class="resolve_button_td">
              <button class="btn btn-success resolved_bug_button" id="bug_<%= bug.id %>_resolved" > Bug Resolved ?</button>
            </td>

       
 -->
         

<!--           <td><%#= bug.user_id %></td> -->
          <td><%= link_to 'Edit', edit_bug_path(bug),class: "btn btn-info" if policy(Bug).edit? %></td>
          <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" if policy(Bug).destroy? %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <br>
  <% if policy(Bug).new?%>
  <%= link_to 'New Bug', new_bug_path,class: "btn btn-info" %>
  <% end %>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form', bug: @bug %>

<%= link_to 'Back', bugs_path , :class => "btn btn-info"%>

app/views/bugs/resolved_bug.html.erb
<div class="container">
	<h2>
		Resolved Bugs
	</h2>
	<table class="table">
		<thead>
			<tr>
			<th>Created By</th>
			<th>Assigned To</th>
			<th>Project</th>
			<th>Bug Title</th>
			<th>Deadline</th>
			<th>Screenshot</th>
			<th>status</th>
			<th>Type</th>
		</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @bug.user.name%></td>
		        <td><%= @bug.assigned_to.name rescue ""%></td>
		        <td><%= @bug.project.name %>  </td>
		        <td><%= @bug.title %></td>
		        <td><%= @bug.deadline %></td>
		        <td><%= image_tag @bug.screenshot_url.to_s %></td>
		        <td><%= @bug.status %></td>
		        <td><%= @bug.bug_type %></td>
			</tr>
			
		</tbody>
	</table>
</div>

app/views/bugs/show.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<!DOCTYPE html>
<html lang="en">
<head>

<body>

<div class="container">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>Project</th>
        <th>Title</th>
        <th>Deadline</th>
        <th>Screenshot</th>
        <th>Status</th>
        <th>Type</th>
        <th>Created By User ID</th>
      </tr>
    </thead>
    <tbody>
      <tr>
<!--         <td><%#= @bug.user.name%></td> -->
        <td><%= @bug.project.name %></td>
        <td><%= @bug.title %></td>
        <td><%= @bug.deadline %></td>
        <td><%= @bug.screenshot %></td>
        <td><%= @bug.bug_type %></td>
        <td><%= @bug.status %></td>
        <td><%= @bug.user_id %></td>
        <td></td>
        <td></td>
      </tr>

    </tbody>

  </table>
  <%= link_to 'Edit', edit_bug_path(@bug) %>
  <%= link_to 'Back', bugs_path %>
</div>

</body>
</html>