config/routes.rb
Rails.application.routes.draw do
  
#  get 'login', to: 'sessions#new'
  get 'profile', to: 'users#show'
  #get 'users/show'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root "homes#index"



####### Adding custom action in bugs controller #######

  resources :bugs do
    collection do
      get :assign_bug
      get :resolved_bug      
    end
  end
  
####### Adding custom action in bugs controller #######


####### Adding custom action in project controller #######

  resources :projects do
  	member do
  		get :add_user
      delete :delete_project_user
  		end
  	end

####### Adding custom action in project controller #######

  resources :projects
  resources :bugs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzilla</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
<!--   	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p> -->
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
      
      <div class="container">
        
        <div class="navbar-header">
          <%= link_to 'Bugzilla', '#', class: 'navbar-brand' %>
        </div>
        
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to 'Home', root_path %>
            </li>
            <% if !user_signed_in? %>
            <li>
              <%= link_to 'Log in', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'Sign up', new_user_registration_path %>
            </li>
            <% else %>
            <li>
              <%= link_to 'Profile',profile_path %>
            </li>
            <li>
              <%= link_to 'Projects',projects_path %>
            </li>
            <li>
              <%= link_to 'Bugs',bugs_path %>
            </li>                        
            <li>
              <li><a>Logged in | <%= current_user.name %> ( <%=current_user.user_type %> ) </a> </li>
              <li>
                <%= link_to 'Log out',destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            </li>
            <% end %>

          </ul>

        </div> 
      </div>
    </nav>


  <div class="container">

    <% flash.each do |type, message| %>
      <div class="alert alert-<%= (type==("notice" || "alert")) ? "info" : type %>"><%= message %></div>
    <% end %>

    <%= yield %>    
  </div>

      </body>
</html>